Automation
kalpanaTech/ProjectMars pull request #3
Opened 2024-10-17 03:05 UTC by kalpanaTech

Hi,
Please find the "Add Languages and Add Skill" automation code for the review. I'm looking forward to some advices to improve my code. I'll appreciate your feedback.
Thanks

2024-10-20 12:45 UTC, amanbansalnz commented on ProjectMars/Feature/Profile.feature
> +This is a platform where users can add and show skills and languages ​​known by users.
can you please split your feature files into features,  language and skills! do this with steps definitions too

2024-10-20 12:45 UTC, amanbansalnz commented on ProjectMars/SpecflowPages/Helpers/CommonMethods.cs
> +    {
no required if its empty

2024-10-20 12:45 UTC, amanbansalnz commented on ProjectMars/SpecflowPages/Helpers/ConstantHelpers.cs
> +    internal class ConstantHelpers
no required if its empty

2024-10-20 12:46 UTC, amanbansalnz commented on ProjectMars/SpecflowPages/Utils/Start.cs
> +            AddLanguage addNewLanguageButtonActionsObj = new AddLanguage();
why do you have this?

2024-10-20 12:50 UTC, amanbansalnz requested changes
Hey, I have reviewed your task please see the pr for the suggested changes to make

2024-10-20 12:50 UTC, amanbansalnz commented on ProjectMars/SpecflowPages/Utils/Start.cs
> +            AddLanguage addNewLanguageButtonActionsObj = new AddLanguage();
you are missing step definitions please this for specflow exmaple https://docs.specflow.org/projects/specflow/en/latest/ui-automation/Selenium-with-Page-Object-Pattern.html

2024-10-20 12:50 UTC, amanbansalnz commented on ProjectMars/Feature/Profile.feature
> +	When I click on the Add New button
i see your do cleanup after each test, but have you cleaned up all data before any test has started?

2024-10-21 22:26 UTC, kalpanaTech commented
Hi Aman, Thank you for your review. I have updated the code based on your suggestions. Could you please take a look?

I previously added the Start.cs page, thinking it was necessary for SpecFlow, but it wasn't needed, so I removed it along with other unnecessary files.
I added a new step to clean up all data before the tests start.
I combined the steps for adding duplicate data into one, instead of two separate steps.

Thanks

2024-10-28 16:01 UTC, merged